name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능하게 추가

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn affected:test --parallel=5

      - name: Build
        run: yarn affected:build --parallel=5
